import type { FiverrOrder } from "./types";

/**
 * Every completed Fiverr order, newest first. Reviews are quoted as the client
 * wrote them. Prices are left out on purpose.
 */
export const orders: FiverrOrder[] = [
  {
    client: "pedfag",
    placed: "2024-04-23",
    delivered: "2024-04-23",
    summary: "Fixed urgent issues on the client's live platform.",
    tags: ["Next.js"],
    rating: 5,
    review: "Very helpful when I was pressed for time and urgently needed to address technical issues.",
  },
  {
    client: "drewjoh",
    placed: "2024-01-09",
    delivered: "2024-01-15",
    summary: "Built a cross-platform mobile app in React Native and Expo.",
    tags: ["React Native", "Expo"],
  },
  {
    client: "alexthedrey",
    placed: "2023-05-08",
    delivered: "2023-12-02",
    summary: "Built DuoBlaze, a head-to-head voting site with accounts, a leaderboard and challenges, on a React front end and a Node.js API.",
    tags: ["React", "Node.js"],
    project: "duoblaze",
  },
  {
    client: "bryonyz",
    placed: "2023-09-20",
    delivered: "2023-10-04",
    summary: "Redesigned the Zodi World home screen around daily and monthly readings.",
    tags: ["React Native", "Expo"],
    project: "zodi-world",
    rating: 5,
    review: "Fast and high quality work as always",
  },
  {
    client: "bryonyz",
    placed: "2023-08-28",
    delivered: "2023-09-12",
    summary: "Built another set of Zodi World features to a detailed spec, with revisions.",
    tags: ["React Native", "Expo"],
    project: "zodi-world",
    rating: 5,
    review: "Always a great experience working with Saidul, who handled complex requirements very well and was willing to make revisions even for very niche use cases.",
  },
  {
    client: "bryonyz",
    placed: "2023-08-17",
    delivered: "2023-08-23",
    summary: "Added the crystal of the day to Zodi World, with sharing.",
    tags: ["React Native", "Expo"],
    project: "zodi-world",
    rating: 5,
    review: "Saidulbadhon is an amazing developer who easily understands requirements and produces high quality results exactly as specified. They always deliver on time or even early, as was the case with this delivery.",
  },
  {
    client: "bryonyz",
    placed: "2023-07-24",
    delivered: "2023-08-16",
    summary: "Added a detail screen for each Zodi World collectible and removed the draw limits.",
    tags: ["React Native", "Expo"],
    project: "zodi-world",
  },
  {
    client: "bryonyz",
    placed: "2023-07-24",
    delivered: "2023-08-12",
    summary: "Added sharing collectibles to Instagram Stories, and fixed sharing on Android.",
    tags: ["React Native", "Expo"],
    project: "zodi-world",
    rating: 5,
    review: "High quality delivery, communicative when some unexpected issues arose and got them resolved quickly.",
  },
  {
    client: "bryonyz",
    placed: "2023-07-14",
    delivered: "2023-07-16",
    summary: "Fixed a bug in the Zodi World delete flow.",
    tags: ["React Native"],
    project: "zodi-world",
    rating: 5,
    review: "Very fast implementation of a new feature, completely perfect result.",
  },
  {
    client: "bryonyz",
    placed: "2023-07-14",
    delivered: "2023-07-16",
    summary: "Fixed a bug on the Zodi World sign choice screen.",
    tags: ["React Native"],
    project: "zodi-world",
    rating: 5,
    review: "Another speedy bug fix and delivery!",
  },
  {
    client: "bryonyz",
    placed: "2023-07-14",
    delivered: "2023-07-16",
    summary: "Fixed another Zodi World bug.",
    tags: ["React Native"],
    project: "zodi-world",
    rating: 5,
    review: "Super fast bug fix, highly recommend.",
  },
  {
    client: "bryonyz",
    placed: "2023-05-19",
    delivered: "2023-07-07",
    summary: "Rebuilt Zodi World by hand in React Native and Expo, from a no-code prototype to an app ready for the App Store and Google Play.",
    tags: ["React Native", "Expo", "Supabase"],
    project: "zodi-world",
    rating: 5,
    review: "I highly recommend saidulbadhon for your mobile app development project. They took my app from a messy prototype to a beautiful finished product, suitable for submission to the stores. They were extremely responsive to my requests and understood the requirements easily, the work was of extremely high quality and they were understanding when I requested revisions. They were also great at keeping me involved in the development and worked with my preferences in mind which I really appreciated. I would definitely hire again.",
  },
  {
    client: "dreadrocksean",
    placed: "2023-05-09",
    delivered: "2023-05-13",
    summary: "Fixed the React Native client of Tell Me What To Play, tracking problems down through its error logs.",
    tags: ["React Native"],
    rating: 4.7,
    review: "Saidul will go above and beyond to satisfy your project requirements. He will even make suggestions outside of that. He takes pride in his work and is very talented. He is an excellent trouble shooter and understands all the tools available for error log scrutiny. He fixed problems for me that many could not. I will definitely rehire.",
  },
  {
    client: "n805248",
    placed: "2023-03-11",
    delivered: "2023-03-14",
    summary: "Built a React user management table with search, sorting, filters and forms to create, edit and delete users.",
    tags: ["React"],
    project: "user-table",
    rating: 5,
    review: "Very good communication and replies quickly, good job!",
  },
  {
    client: "pedfag",
    placed: "2022-10-13",
    delivered: "2023-03-05",
    summary: "Built RealSelect, a Next.js real estate referral site for home buyers, sellers and partner agents.",
    tags: ["Next.js", "Node.js"],
    project: "noven-realselect",
    rating: 5,
    review: "I had a great experience working with this seller on my project. He was extremely professional and took the time to really listen to my needs and understand the specific requirements of the project.",
  },
  {
    client: "teakong",
    placed: "2022-12-10",
    delivered: "2023-01-25",
    summary: "Built a job tracking dashboard for DSL Elektronika: admins add workers and assign jobs, and workers see their jobs and earnings.",
    tags: ["React", "Node.js", "MongoDB"],
    project: "dsl-elektronika",
  },
  {
    client: "nomad3526",
    placed: "2022-11-10",
    delivered: "2022-12-17",
    summary: "Added an admin dashboard and company job posting to Campus Japan, and deployed it on AWS Amplify.",
    tags: ["Next.js", "Node.js", "AWS"],
    project: "campus-japan",
    rating: 5,
    review: "Saichul is the best full stack developer out there. He balances his school and work so perfectly and delivers on time. Will always prefer him to do my jobs!",
  },
  {
    client: "billias86",
    placed: "2022-11-20",
    delivered: "2022-11-21",
    summary: "Shipped a further MarseFly update, live on the web.",
    tags: ["React", "Node.js"],
    project: "marsefly",
  },
  {
    client: "nomad3526",
    placed: "2022-10-15",
    delivered: "2022-11-07",
    summary: "Built the Campus Japan applicant dashboard, help center and settings.",
    tags: ["Next.js", "Node.js"],
    project: "campus-japan",
    rating: 5,
    review: "Saidhul was great as usual !",
  },
  {
    client: "billias86",
    placed: "2022-04-04",
    delivered: "2022-10-12",
    summary: "Built MarseFly over several milestones: sign-in with Google and Facebook, photo and video albums, a map and connections.",
    tags: ["React", "Node.js", "MongoDB"],
    project: "marsefly",
    rating: 5,
    review: "It was nice working with him. We had good communication and delivered what i expected.",
  },
  {
    client: "nomad3526",
    placed: "2022-09-19",
    delivered: "2022-10-12",
    summary: "Built the first part of Campus Japan: the landing page, job search and company pages.",
    tags: ["Next.js", "Node.js"],
    project: "campus-japan",
    rating: 5,
    review: "Saidhul is awesome. In addition to being a developer, he has great taste in UI design! Awesome!",
  },
  {
    client: "puzzleapp",
    placed: "2022-04-30",
    delivered: "2022-08-24",
    summary: "Built the Slow Puzzle app in React Native and Expo, with sign-up, rewards and an admin dashboard.",
    tags: ["React Native", "Expo", "MongoDB", "AWS"],
    project: "slow-puzzle",
  },
  {
    client: "nguyenst3r",
    placed: "2022-04-27",
    delivered: "2022-05-02",
    summary: "Built Encrypt-It, a one-page tool that encrypts text with a choice of ciphers.",
    tags: ["JavaScript"],
  },
  {
    client: "stefansec",
    placed: "2022-04-10",
    delivered: "2022-04-17",
    summary: "Built a pit lane countdown board for a motorsport team, with race timers and refuelling calls.",
    tags: ["React"],
    project: "pit-lane",
    rating: 5,
    review: "Saidulbadhon created a web app for us. He understood all of our requriemtents and aked the right questions when things were not clear. First delivery was fast and high quality, but we needed a revision to adjust the apps logic. Saidulbadhon implemented the changes again very fast and provided us a high quality web app! We recommend his service!",
  },
  {
    client: "nguyenst3r",
    placed: "2022-04-14",
    delivered: "2022-04-17",
    summary: "Built a small Node.js and Express API that reads route and query parameters.",
    tags: ["Node.js", "Express"],
  },
  {
    client: "jfiver1",
    placed: "2021-10-29",
    delivered: "2022-04-14",
    summary: "Built WarmMatch, a React Native app with Twitter sign-in and its API, and delivered the iOS and Android builds.",
    tags: ["React Native", "Expo", "Node.js"],
    rating: 5,
    review: "excellent seller! he got the job done and I highly recommend service.",
  },
  {
    client: "jameschae",
    placed: "2022-03-30",
    delivered: "2022-04-06",
    summary: "Built Privil, a web app for creating, saving and printing QR codes, with accounts, and launched it at privil.link.",
    tags: ["React", "Node.js"],
    project: "privil",
    rating: 5,
    review: "Saidulbadhon is such a professional full stack web developer. He is very good at communication too. He was very fast in understanding my needs and able to deliver what I needed perfectly. He was willing to get my feedbacks and have it reflected in delivery nicely. I really enjoyed working with him and hope to work with him again in the near future! I highly recommend Saidulbadhon for what he does in web development. Thanks a lot!",
  },
  {
    client: "nodetechnologie",
    placed: "2022-03-30",
    delivered: "2022-03-30",
    summary: "Built a form builder and fixed bugs in an existing React app.",
    tags: ["React"],
    rating: 5,
    review: "Excellent work in fast time",
  },
  {
    client: "nodetechnologie",
    placed: "2022-03-28",
    delivered: "2022-03-29",
    summary: "Added features to an existing React app.",
    tags: ["React"],
    rating: 5,
    review: "Thanks for your great work! I really appreciate our collaboration",
  },
  {
    client: "pedfag",
    placed: "2022-02-24",
    delivered: "2022-03-11",
    summary: "Built the Noven admin dashboard for services, projects, the library, contacts, proposal requests and the newsletter, and deployed it.",
    tags: ["React", "Node.js"],
    project: "noven-realselect",
    rating: 5,
    review: "It was great working with this seller. He is professional with good communication skills. Thank you.",
  },
  {
    client: "pedfag",
    placed: "2022-01-20",
    delivered: "2022-01-21",
    summary: "Fixed issues on the Noven website.",
    tags: ["Next.js"],
    project: "noven-realselect",
    rating: 5,
    review: "Seller is professional and communicate effectively to reach project goals.",
  },
  {
    client: "pedfag",
    placed: "2021-09-14",
    delivered: "2021-12-22",
    summary: "Built the Noven Consulting website in Next.js, with a Node.js API.",
    tags: ["Next.js", "Node.js"],
    project: "noven-realselect",
    rating: 5,
    review: "Great experience with Saidul. He was professional and patient during the entire time that we worked on the project. He delivered a high-quality project.",
  },
  {
    client: "jreylouis",
    placed: "2021-12-01",
    delivered: "2021-12-07",
    summary: "Built SXM Smart Shopping, a shopping app in React Native and Expo.",
    tags: ["React Native", "Expo"],
  },
  {
    client: "pietrik13",
    placed: "2021-10-17",
    delivered: "2021-10-19",
    summary: "Audited an old React Native app on Expo 31 and class components, and scoped a rewrite with hooks.",
    tags: ["React Native"],
    rating: 5,
    review: "Very professional. He's skilled and prepared to support you. Highly recommended",
  },
  {
    client: "aswadgul",
    placed: "2021-10-16",
    delivered: "2021-10-16",
    summary: "Finished a task on the client's app.",
    tags: ["React"],
    rating: 5,
    review: "The guy is really good at his work, ordered a gig with a task now I'm sending all my tasks related to my app to this guy. Keep it up buddy",
  },
  {
    client: "joshke",
    placed: "2021-09-23",
    delivered: "2021-10-08",
    summary: "Built a React Native app in two versions, one bare and one on Expo.",
    tags: ["React Native", "Expo"],
  },
  {
    client: "lee_tech",
    placed: "2021-09-25",
    delivered: "2021-09-26",
    summary: "Built a React app for browsing the Metropolitan Museum of Art's collection through its open API.",
    tags: ["React"],
    rating: 5,
    review: "Excellent work and quality!",
  },
  {
    client: "pinigai000",
    placed: "2021-08-20",
    delivered: "2021-08-29",
    summary: "Delivered an updated version of a React and Node.js app.",
    tags: ["React", "Node.js"],
  },
  {
    client: "gnwosu",
    placed: "2021-08-03",
    delivered: "2021-08-26",
    summary: "Built FlyBurgains, a React website with a Node.js and MongoDB API.",
    tags: ["React", "Node.js", "MongoDB"],
  },
  {
    client: "lee_tech",
    placed: "2021-08-23",
    delivered: "2021-08-24",
    summary: "Built a React website with a Node.js API.",
    tags: ["React", "Node.js"],
    rating: 5,
    review: "Great service and communication skills. Very satisfied! Thanks.",
  },
  {
    client: "alsijfapo",
    placed: "2021-08-09",
    delivered: "2021-08-20",
    summary: "Delivered a JavaScript web project.",
    tags: ["JavaScript"],
    rating: 5,
    review: "The best developer.",
  },
  {
    client: "angelomtch",
    placed: "2021-08-03",
    delivered: "2021-08-04",
    summary: "Added streaming songs from an API to a React Native music player, with an Express server to host them.",
    tags: ["React Native", "Express"],
    rating: 5,
    review: "Really great work, He delivered the work one day early Great experience, Awesome service !!!!!!",
  },
  {
    client: "usagi29",
    placed: "2021-07-26",
    delivered: "2021-07-27",
    summary: "Built a React Native and Expo app, tested on iOS and Android.",
    tags: ["React Native", "Expo"],
    rating: 5,
    review: "good experience and also good to work with.",
  },
  {
    client: "mohitkaranwal",
    placed: "2021-07-11",
    delivered: "2021-07-23",
    summary: "Designed and built a Spaces page in React, then refined it with the client's designer.",
    tags: ["React"],
    rating: 5,
    review: "Excellent experience",
  },
  {
    client: "angelomtch",
    placed: "2021-07-02",
    delivered: "2021-07-05",
    summary: "Built a React Native music player for songs stored on the phone.",
    tags: ["React Native"],
  },
  {
    client: "davidatavocado",
    placed: "2021-06-09",
    delivered: "2021-06-28",
    summary: "Built a draggable React Native chart of savings and the breakeven point, year by year.",
    tags: ["React Native"],
    project: "savings-chart",
  },
  {
    client: "angelomtch",
    placed: "2021-06-23",
    delivered: "2021-06-24",
    summary: "Redesigned the home screen buttons of a React Native app and wired up their navigation.",
    tags: ["React Native", "TypeScript"],
    rating: 5,
    review: "Excellent service, the delivery was better than expected. He is very patient, really professional and really good at coding. Looking forward working again with him. I recommend this seller !!!!1",
  },
  {
    client: "seoexpert0900",
    placed: "2021-05-31",
    delivered: "2021-06-05",
    summary: "Built and published an Android game on Google Play.",
    tags: ["React Native"],
    rating: 5,
    review: "Great experience!! I recommend this seller he is expert. thanks",
  },
  {
    client: "engio1",
    placed: "2021-05-06",
    delivered: "2021-05-12",
    summary: "Fixed issues in the Submission League mobile app.",
    tags: ["React Native"],
  },
  {
    client: "user88733026",
    placed: "2021-05-06",
    delivered: "2021-05-12",
    summary: "Shipped three more versions of the Duke Health React app and Node.js API.",
    tags: ["React", "Node.js"],
  },
  {
    client: "engio1",
    placed: "2021-05-03",
    delivered: "2021-05-05",
    summary: "Updated the Submission League mobile app.",
    tags: ["React Native"],
    rating: 5,
    review: "Excellent service!",
  },
  {
    client: "engio1",
    placed: "2021-04-25",
    delivered: "2021-05-03",
    summary: "Delivered the final stage of Submission League.",
    tags: ["React Native"],
    rating: 5,
    review: "Excellent service, delivered beyond expectations. Looking forward to working agin",
  },
  {
    client: "user88733026",
    placed: "2021-04-23",
    delivered: "2021-04-29",
    summary: "Added Sequelize database migrations to the Duke Health API.",
    tags: ["Node.js", "Sequelize"],
  },
  {
    client: "user88733026",
    placed: "2021-03-03",
    delivered: "2021-04-22",
    summary: "Built Duke Health, a React web app with a Node.js API, and moved its database to Microsoft Azure.",
    tags: ["React", "Node.js", "Azure"],
    rating: 5,
    review: "Awesome service. Very patient and great design!",
  },
  {
    client: "engio1",
    placed: "2021-03-09",
    delivered: "2021-04-19",
    summary: "Built the Submission League mobile app in React Native: onboarding, sign-up and login, matches, tables and results.",
    tags: ["React Native", "Expo"],
  },
  {
    client: "alirezaroyaie",
    placed: "2021-02-28",
    delivered: "2021-03-13",
    summary: "Built the vFitter website and its Node.js REST API on AWS, and a 3D model viewer with QR codes.",
    tags: ["React", "Node.js", "AWS"],
    rating: 5,
    review: "THIS GUY IS AN ABSOLUTE LEGEND. he codes like he is playing a musical instrument. his skills are magical in REACT JS, NODE JS, REST API and database. I am familiar with coding and designing and I tell you now that you are hiring a full package. the final delivery shocked me. EVERYTHING WORKS. I am really happy and I am sorry because he is gonna be working on my projects from now on :D :D :D",
  },
  {
    client: "harryneodoc",
    placed: "2021-02-25",
    delivered: "2021-03-09",
    summary: "Built a React app for Neodoc.",
    tags: ["React"],
    rating: 5,
    review: "Work was delivered early and to a high quality, better than expected. Would happily work with Saidul again! Diamond in the rough from this platform!",
  },
  {
    client: "jakobmarkryd",
    placed: "2021-02-25",
    delivered: "2021-03-07",
    summary: "Built WashAway, a React app.",
    tags: ["React"],
    rating: 5,
    review: "Easy to work with, good communcation and did everything in time.",
  },
  {
    client: "booogle",
    placed: "2021-02-28",
    delivered: "2021-03-01",
    summary: "Reviewed stylin, an open-source CSS-in-JS library, with feedback on its documentation.",
    tags: ["CSS"],
  },
  {
    client: "user40645290",
    placed: "2021-02-19",
    delivered: "2021-02-25",
    summary: "Built Go-Thru, a responsive, component-based React web app driven by JSON data.",
    tags: ["React"],
    rating: 5,
    review: "Awesome job!",
  },
  {
    client: "marksytk",
    placed: "2021-02-19",
    delivered: "2021-02-24",
    summary: "Built a front end and a Node.js back end.",
    tags: ["JavaScript", "Node.js"],
  },
  {
    client: "aaronhassett",
    placed: "2021-02-11",
    delivered: "2021-02-19",
    summary: "Built and hosted the RosterStack website.",
    tags: ["React"],
    rating: 5,
    review: "He did a great job and had great communication",
  },
  {
    client: "ritik_12345",
    placed: "2021-02-14",
    delivered: "2021-02-19",
    summary: "Built Sakial, a React app.",
    tags: ["React"],
    rating: 5,
    review: "it was a great and friendly behaviour and also the work done is very satisfactory it was nice dealing with saldulbadhon",
  },
  {
    client: "user40645290",
    placed: "2021-01-19",
    delivered: "2021-01-25",
    summary: "Built HubJobs, a three-page React job site.",
    tags: ["React"],
    rating: 5,
    review: "🚀 This was certainly one of the best jobs I have ever found here at Fiverr. I will continue doing work on React just because of him! I surprised myself positively. Thanks!",
  },
  {
    client: "josephsiddall",
    placed: "2020-10-16",
    delivered: "2020-10-19",
    summary: "Built a React and TypeScript footer component with social links, themes and dark mode.",
    tags: ["React", "TypeScript"],
  },
];
